# Generated by Django 4.0 on 2021-12-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='lastt_name',
            new_name='last_name',
        ),
    ]
